-- users.sql
﻿ALTER TABLE users ALTER COLUMN id RESTART WITH 1100;
﻿ALTER TABLE userGroups ALTER COLUMN id RESTART WITH 1200;
﻿ALTER TABLE tokens ALTER COLUMN id RESTART WITH 1300;

-- address.sql
﻿ALTER TABLE countries ALTER COLUMN id RESTART WITH 2000;
﻿ALTER TABLE states ALTER COLUMN id RESTART WITH 2100;
﻿ALTER TABLE districts ALTER COLUMN id RESTART WITH 2200;
﻿ALTER TABLE cityTypes ALTER COLUMN id RESTART WITH 2300;
﻿ALTER TABLE cities ALTER COLUMN id RESTART WITH 2400;
﻿ALTER TABLE postcodes ALTER COLUMN id RESTART WITH 2500;
﻿ALTER TABLE locationTypes ALTER COLUMN id RESTART WITH 2600;

-- partner.sql
﻿ALTER TABLE appointments ALTER COLUMN id RESTART WITH 3000;
﻿ALTER TABLE contactTypes ALTER COLUMN id RESTART WITH 3100;
﻿ALTER TABLE partners ALTER COLUMN id RESTART WITH 3200;
﻿ALTER TABLE partnerFiles ALTER COLUMN id RESTART WITH 3300;
﻿ALTER TABLE contacts ALTER COLUMN id RESTART WITH 3400;
