create table countries (
  id smallint not null generated by default as identity
, name varchar(63) not null
, fullname varchar(255) not null
);
alter table countries add constraint pk_countries primary key(id);

create table states (
  id int not null generated by default as identity
, countryId int not null
, name varchar(63) not null
, fullname varchar(255) not null
);
alter table states add constraint pk_states primary key(id);
alter table states add constraint fk_states_countries foreign key(countryId) references countries(id);

create table districts (
  id int not null generated by default as identity
, stateId int not null
, name varchar(63) not null
, fullname varchar(255) not null
);
alter table districts add constraint pk_district primary key(id);
alter table districts add constraint fk_districts_states foreign key(stateId) references states(id);

create table cityTypes (
  id smallint not null generated by default as identity
, name varchar(8) not null
, fullname varchar(47) not null
);
alter table cityTypes add constraint pk_cityTypes primary key(id);

create table cities (
  id int not null generated by default as identity
, typeId smallint --not null
, stateId int not null
, districtId int --not null
, name varchar(127) not null
);
alter table cities add constraint pk_cities primary key(id);
alter table cities add constraint fk_cities_cityTypes foreign key(typeId) references cityTypes(id);
alter table cities add constraint fk_cities_states foreign key(stateId) references states(id);
alter table cities add constraint fk_cities_districts foreign key(districtId) references districts(id);

create table postcodes (
  id int not null generated by default as identity
, districtId int --not null
, cityId int not null
, postcode varchar(11) not null
);
alter table postcodes add constraint pk_postcodes primary key(id);
alter table postcodes add constraint fk_postcodes_districts foreign key(districtId) references districts(id);
alter table postcodes add constraint fk_postcodes_cities foreign key(cityId) references cities(id);
