--defaultAccess: 0-ALL, 1-AUTHENTICATED, 2-NOBODY
--updateFor: 0-read, 1-update
--typ: 0-class, 1-field, 2-method,URL
insert into roles(defaultAccess, isUrl, orphan, updateFor, objName, id, name, description) values
 (0,0,0,0,'biz.softfor.partner.jpa.Partner.partnerName',roleId(0,'biz.softfor.partner.jpa.Partner.partnerName',1),'Partner#partnerName','biz.softfor.partner.jpa Partner#partnerName')
,(0,0,0,1,'biz.softfor.partner.jpa.Partner.partnerName',roleId(1,'biz.softfor.partner.jpa.Partner.partnerName',1),'Partner#partnerName (update)','biz.softfor.partner.jpa Partner#partnerName (update)')
,(0,0,0,0,'biz.softfor.partner.jpa.Partner.partnerDetails',roleId(0,'biz.softfor.partner.jpa.Partner.partnerDetails',1),'Partner#partner details','biz.softfor.partner.jpa Partner#partner details')
,(0,0,0,1,'biz.softfor.partner.jpa.Partner.partnerDetails',roleId(1,'biz.softfor.partner.jpa.Partner.partnerDetails',1),'Partner#partner details (update)','biz.softfor.partner.jpa Partner#partner details (update)')
,(0,0,0,0,'biz.softfor.partner.jpa.Partner.locationType',roleId(0,'biz.softfor.partner.jpa.Partner.locationType',1),'Partner#location type','biz.softfor.partner.jpa Partner#location type')
,(0,0,0,1,'biz.softfor.partner.jpa.Partner.locationType',roleId(1,'biz.softfor.partner.jpa.Partner.locationType',1),'Partner#location type (update)','biz.softfor.partner.jpa Partner#location type (update)')
,(0,0,0,0,'biz.softfor.address.jpa.Country.name',roleId(0,'biz.softfor.address.jpa.Country.name',1),'Country#name','biz.softfor.address.jpa.Country#name')
,(0,0,0,0,'biz.softfor.address.jpa.Country.fullname',roleId(0,'biz.softfor.address.jpa.Country.fullname',1),'Country#fullname','biz.softfor.address.jpa.Country#fullname')
,(1,0,0,0,'biz.softfor.user.spring.rest.testassets.TezztEntity.authorized',roleId(0,'biz.softfor.user.spring.rest.testassets.TezztEntity.authorized',1),'Authorized','Authorized')
,(2,0,1,1,'biz.softfor.user.spring.rest.testassets.TezztEntity.authorized',roleId(1,'biz.softfor.user.spring.rest.testassets.TezztEntity.authorized',1),'Authorized (update)','Authorized (update)')
;
insert into userGroups(name) values
 ('TezztMgr')--2
,('TezztUser')--3
;
insert into roles_groups(groupId, roleId) values
 (1,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.partnerName' AND updateFor=0))
,(1,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.partnerName' AND updateFor=1))
,(1,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.partnerDetails' AND updateFor=0))
,(1,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.partnerDetails' AND updateFor=1))
,(1,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.locationType' AND updateFor=0))
,(1,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.locationType' AND updateFor=1))
,(2,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.locationType' AND updateFor=0))
,(2,(SELECT id from roles WHERE objName='biz.softfor.partner.jpa.Partner.locationType' AND updateFor=1))
,(3,(SELECT id from roles WHERE objName='biz.softfor.address.jpa.Country.name' AND updateFor=0))
,(3,(SELECT id from roles WHERE objName='biz.softfor.address.jpa.Country.fullname' AND updateFor=0))
;
insert into partners(typ, locationTypeId, postcodeId, parentId, partnerName, partnerRegdate, partnerRegcode, address, partnerFullname) values
 (1,null,null,null,'testPartner','2022-01-12','1111111111','Ship st., 8','Test Partner')--1
;
insert into users(personId, username, password, email) values
 (1,'admin','$2a$10$yA.Nf8JE6bITztDwXalVSeWYfRLZ8Skp4V5JBO.mwxCe.i.xI46pe','admin@t.co')--1
,(1,'testDefaultAccess','$2a$10$ZF97qp0VsyzZusmVgXxYs.IFSBCrf0ahhCrKGGNqecSUAGqBF3HWK','testDefaultAccess@t.co')--2
;
insert into users_groups(userId, groupId) values
 (1, 1)
;
INSERT INTO countries(id,name,fullname) VALUES
 (1,'Afghanistan','Islamic Republic of Afghanistan')
;
INSERT INTO states(id,countryId,name,fullname) VALUES
 (1,1,'KAB','Kabul')
;
insert into partnerDetails(id, note) values
 (1,'Test note')
;
insert into personDetails(id, passportSeries, passportNumber, passportDate, middlename, passportIssued) values
 (1,'QQ','333333','1986-09-21','Frost','Dallas department')
;
create table testentities (
 id int not null generated by default as identity
,everybody varchar(15) default null
,authorized varchar(15) default null
,nobody varchar(15) default null
);
insert into testentities(everybody, authorized, nobody) values
 ('everybody1','authorized1','nobody1')--1
;
