INSERT INTO countries(id,name,fullname) VALUES
(1,'Afghanistan','Islamic Republic of Afghanistan'),
(2,'Albania','Republic of Albania'),
(3,'Algeria','People''s Democratic Republic of Algeria'),
(4,'Andorra','Principality of Andorra'),
(5,'Angola','Republic of Angola'),
(6,'Antigua and Barbuda','Antigua and Barbuda'),
(7,'Argentina','Argentine Republic'),
(8,'Armenia','Republic of Armenia'),
(9,'Australia','Commonwealth of Australia'),
(10,'Austria','Republic of Austria'),
(11,'Azerbaijan','Republic of Azerbaijan'),
(12,'Bahamas','Commonwealth of The Bahamas'),
(13,'Bahrain','Kingdom of Bahrain'),
(14,'Bangladesh','People''s Republic of Bangladesh'),
(15,'Barbados','Barbados'),
(16,'Belarus','Republic of Belarus'),
(17,'Belgium','Kingdom of Belgium'),
(18,'Belize','Belize'),
(19,'Benin','Republic of Benin'),
(20,'Bhutan','Kingdom of Bhutan'),
(21,'Bolivia','Plurinational State of Bolivia'),
(22,'Bosnia and Herzegovina','Bosnia and Herzegovina'),
(23,'Botswana','Republic of Botswana'),
(24,'Brazil','Federative Republic of Brazil'),
(25,'Brunei','Nation of Brunei, the Abode of Peace'),
(26,'Bulgaria','Republic of Bulgaria'),
(27,'Burkina Faso','Burkina Faso'),
(28,'Burundi','Republic of Burundi'),
(29,'Cambodia','Kingdom of Cambodia'),
(30,'Cameroon','Republic of Cameroon'),
(31,'Canada','Canada'),
(32,'Cape Verde','Republic of Cabo Verde'),
(33,'Central African Republic','Central African Republic'),
(34,'Chad','Republic of Chad'),
(35,'Chile','Republic of Chile'),
(36,'China','People''s Republic of China'),
(37,'Colombia','Republic of Colombia'),
(38,'Comoros','Union of the Comoros'),
(39,'Congo, Republic of the','Republic of the Congo'),
(40,'Congo, Democratic Republic of the','Democratic Republic of the Congo'),
(41,'Cook Islands','Cook Islands'),
(42,'Costa Rica','Republic of Costa Rica'),
(43,'Croatia','Republic of Croatia'),
(44,'Cuba','Republic of Cuba'),
(45,'Cyprus','Republic of Cyprus'),
(46,'Czech Republic','Czech Republic'),
(47,'Denmark','Kingdom of Denmark'),
(48,'Djibouti','Republic of Djibouti'),
(49,'Dominica','Commonwealth of Dominica'),
(50,'Dominican Republic','Dominican Republic'),
(51,'Ecuador','Republic of Ecuador'),
(52,'Egypt','Arab Republic of Egypt'),
(53,'El Salvador','Republic of El Salvador'),
(54,'Equatorial Guinea','Republic of Equatorial Guinea'),
(55,'Eritrea','State of Eritrea'),
(56,'Estonia','Republic of Estonia'),
(57,'Eswatini','Kingdom of Eswatini'),
(58,'Ethiopia','Federal Democratic Republic of Ethiopia'),
(59,'Fiji','Republic of Fiji'),
(60,'Finland','Republic of Finland'),
(61,'France','French Republic'),
(62,'Gabon','Gabonese Republic'),
(63,'Gambia','Republic of The Gambia[17]'),
(64,'Georgia','Georgia'),
(65,'Germany','Federal Republic of Germany'),
(66,'Ghana','Republic of Ghana'),
(67,'Greece','Hellenic Republic'),
(68,'Grenada','Grenada'),
(69,'Guatemala','Republic of Guatemala'),
(70,'Guinea','Republic of Guinea'),
(71,'Guinea-Bissau','Republic of Guinea-Bissau'),
(72,'Guyana','Co-operative Republic of Guyana'),
(73,'Haiti','Republic of Haiti'),
(74,'Honduras','Republic of Honduras'),
(75,'Hungary','Hungary'),
(76,'Iceland','Iceland'),
(77,'India','Republic of India'),
(78,'Indonesia','Republic of Indonesia'),
(79,'Iran','Islamic Republic of Iran'),
(80,'Iraq','Republic of Iraq'),
(81,'Ireland','Ireland'),
(82,'Israel','State of Israel'),
(83,'Italy','Italian Republic'),
(84,'Cote D''Ivoire','Republic of Cote D''Ivoire'),
(85,'Jamaica','Jamaica'),
(86,'Japan','Japan'),
(87,'Jordan','Hashemite Kingdom of Jordan'),
(88,'Kazakhstan','Republic of Kazakhstan'),
(89,'Kenya','Republic of Kenya'),
(90,'Kiribati','Republic of Kiribati'),
(91,'Korea, North','Democratic People''s Republic of Korea'),
(92,'Korea, South','Republic of Korea'),
(93,'Kosovo','Republic of Kosovo'),
(94,'Kuwait','State of Kuwait'),
(95,'Kyrgyzstan','Kyrgyz Republic'),
(96,'Laos','Lao People''s Democratic Republic'),
(97,'Latvia','Republic of Latvia'),
(98,'Lebanon','Lebanese Republic'),
(99,'Lesotho','Kingdom of Lesotho'),
(100,'Liberia','Republic of Liberia'),
(101,'Libya','State of Libya'),
(102,'Liechtenstein','Principality of Liechtenstein'),
(103,'Lithuania','Republic of Lithuania'),
(104,'Luxembourg','Grand Duchy of Luxembourg'),
(105,'Madagascar','Republic of Madagascar'),
(106,'Malawi','Republic of Malawi'),
(107,'Malaysia','Malaysia'),
(108,'Maldives','Republic of Maldives'),
(109,'Mali','Republic of Mali'),
(110,'Malta','Republic of Malta'),
(111,'Marshall Islands','Republic of the Marshall Islands'),
(112,'Mauritania','Islamic Republic of Mauritania'),
(113,'Mauritius','Republic of Mauritius'),
(114,'Mexico','United Mexican States'),
(115,'Micronesia','Federated States of Micronesia'),
(116,'Moldova','Republic of Moldova'),
(117,'Monaco','Principality of Monaco'),
(118,'Mongolia','Mongolia'),
(119,'Montenegro','Montenegro'),
(120,'Morocco','Kingdom of Morocco'),
(121,'Mozambique','Republic of Mozambique'),
(122,'Myanmar','Republic of the Union of Myanmar'),
(123,'Namibia','Republic of Namibia'),
(124,'Nauru','Republic of Nauru'),
(125,'Nepal','Federal Democratic Republic of Nepal'),
(126,'Netherlands','Kingdom of the Netherlands'),
(127,'New Zealand','New Zealand'),
(128,'Nicaragua','Republic of Nicaragua'),
(129,'Niger','Republic of Niger'),
(130,'Nigeria','Federal Republic of Nigeria'),
(131,'Niue','Niue'),
(132,'North Macedonia','Republic of North Macedonia'),
(133,'Norway','Kingdom of Norway'),
(134,'Oman','Sultanate of Oman'),
(135,'Pakistan','Islamic Republic of Pakistan'),
(136,'Palau','Republic of Palau'),
(137,'Palestine','State of Palestine'),
(138,'Panama','Republic of Panama'),
(139,'Papua New Guinea','Independent State of Papua New Guinea'),
(140,'Paraguay','Republic of Paraguay'),
(141,'Peru','Republic of Peru'),
(142,'Philippines','Republic of the Philippines'),
(143,'Poland','Republic of Poland'),
(144,'Portugal','Portuguese Republic'),
(145,'Qatar','State of Qatar'),
(146,'Romania','Romania'),
(147,'Russia','Russian Federation'),
(148,'Rwanda','Republic of Rwanda'),
(149,'Sahrawi Arab Democratic Republic','Sahrawi Arab Democratic Republic'),
(150,'Saint Kitts and Nevis','Federation of Saint Christopher and Nevis'),
(151,'Saint Lucia','Saint Lucia'),
(152,'Saint Vincent and the Grenadines','Saint Vincent and the Grenadines'),
(153,'Samoa','Independent State of Samoa'),
(154,'San Marino','Republic of San Marino'),
(155,'Saudi Arabia','Kingdom of Saudi Arabia'),
(156,'Senegal','Republic of Senegal'),
(157,'Serbia','Republic of Serbia'),
(158,'Seychelles','Republic of Seychelles'),
(159,'Sierra Leone','Republic of Sierra Leone'),
(160,'Singapore','Republic of Singapore'),
(161,'Slovakia','Slovak Republic'),
(162,'Slovenia','Republic of Slovenia'),
(163,'Solomon Islands','Solomon Islands'),
(164,'Somalia','Federal Republic of Somalia'),
(165,'Somaliland','Republic of Somaliland'),
(166,'South Africa','Republic of South Africa'),
(167,'South Sudan','Republic of South Sudan'),
(168,'Spain','Kingdom of Spain'),
(169,'Sri Lanka','Democratic Socialist Republic of Sri Lanka'),
(170,'Sudan','Republic of the Sudan'),
(171,'Suriname','Republic of Suriname'),
(172,'Sweden','Kingdom of Sweden'),
(173,'Switzerland','Swiss Confederation'),
(174,'Syria','Syrian Arab Republic'),
(175,'Sao Tome and Principe','Democratic Republic of Sao Tome and Principe'),
(176,'Taiwan','Republic of China'),
(177,'Tajikistan','Republic of Tajikistan'),
(178,'Tanzania','United Republic of Tanzania'),
(179,'Thailand','Kingdom of Thailand'),
(180,'Timor-Leste','Democratic Republic of Timor-Leste'),
(181,'Togo','Togolese Republic'),
(182,'Tonga','Kingdom of Tonga'),
(183,'Trinidad and Tobago','Republic of Trinidad and Tobago'),
(184,'Tunisia','Republic of Tunisia'),
(185,'Turkey','Republic of Turkey'),
(186,'Turkmenistan','Turkmenistan'),
(187,'Tuvalu','Tuvalu'),
(188,'Uganda','Republic of Uganda'),
(189,'Ukraine','Ukraine'),
(190,'United Arab Emirates','United Arab Emirates'),
(191,'United Kingdom','United Kingdom of Great Britain and Northern Ireland'),
(192,'United States','United States of America'),
(193,'Uruguay','Oriental Republic of Uruguay'),
(194,'Uzbekistan','Republic of Uzbekistan'),
(195,'Vanuatu','Republic of Vanuatu'),
(196,'Vatican City','Vatican City State'),
(197,'Venezuela','Bolivarian Republic of Venezuela'),
(198,'Vietnam','Socialist Republic of Vietnam'),
(199,'Yemen','Republic of Yemen'),
(200,'Zambia','Republic of Zambia'),
(201,'Zimbabwe','Republic of Zimbabwe')
;
ALTER TABLE countries ALTER COLUMN id RESTART WITH 202;
