# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    paths:
#      - src
#  pull_request:
#    branches: [ "main" ]
#    paths:
#      - src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: maven

    - name: Install BOM
      run: mvn -B install --file biz.softfor.bom/pom.xml

    - name: Clean Vaadin Demo
      run: |
        mvn clean vaadin:clean-frontend --file biz.softfor.vaadin.demo/pom.xml
        rm -f biz.softfor.vaadin.demo/package-lock.json biz.softfor.vaadin.demo/package.json biz.softfor.vaadin.demo/tsconfig.json biz.softfor.vaadin.demo/types.d.ts biz.softfor.vaadin.demo/vite.config.ts biz.softfor.vaadin.demo/vite.generated.ts

    - name: Build all
      run: mvn -B -DskipTests clean install

    - name: Build Vaadin Demo frontend
      run: mvn vaadin:build-frontend --file biz.softfor.vaadin.demo/pom.xml

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - run: chrome --version

    - name: Test
      run: mvn -B test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
